### ISSUE TITLE
Facility bulk upsert: Unable to add location

### ISSUE THREAD

**Issue by afzalIbnSH** [coronasafe/care#94] opened 2020-03-25 08:06 UTC
![Screenshot 2020-03-25 at 1 36 13 PM](https://user-images.githubusercontent.com/45993339/77514897-9fe92900-6e9d-11ea-920f-0b61cc572f8e.png)

**Comment by afzalIbnSH** [comment] 2020-03-25 08:06
I can fix this

**Comment by anroopak** [comment] 2020-03-25 09:19
Please make sure that it is a non-required field. The API is mostly used by a tool to bulk upload data, which may not have the Location data

**Comment by afzalIbnSH** [comment] 2020-03-25 09:57
Since the admins seems to be busy and I might get busy later, I'm going ahead and doing this.

**Comment by vigneshhari** [comment] 2020-03-25 10:41
@anroopak check if the problem is fixed , if so i'll close the issue

**Comment by anroopak** [comment] 2020-03-25 16:39
@vigneshhari verified

**Closed** 2020-03-25 16:40 UTC
Labels: Assigned, bug
